def h = gradle.gradleUserHomeDir
new File(settingsDir, "PRIVADO_GRADLE_HOME.txt").text =
    "gradleUserHomeDir=" + h + "\n" +
    "probe present=" + new File(h, "init.d/privado-probe.gradle").exists() + "\n"
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "AppToDemoStaticCodeAnalysis"
include ':app'
